### PR TITLE
Fixes #147: Likes/Thanks are not merged upon User ID merge

### LINKED ISSUE #147: Likes/Thanks are not merged upon User ID merge
If we merge 2 User IDs, the merged ID will lost likes and the other ID which will remain will have its Likes.

Please add module which will support merge of likes received and given of Thank you/Like plugin upon User ID merge.

Thanks

### PR DESCRIPTION
**Pull request by lairdshaw**
Fixes #147: Likes/Thanks are not merged upon User ID merge

### CODE REVIEW

**Comment by Eldenroot** [comment]
At the first view you had covered all places as we discussed earlier. I tested it only one time - merge two users, both of them had 2 likes, one received like from the second user. After merge all seems to be fine.

We can merge this, release 2.4.0 (or 3.0.0 version - we have a lot of changes and new features, rewrite etc. what do you think? It would be maybe better, because update script is a whole new feature which suits better to a major version). Thank you for your contribution again!

**Comment by lairdshaw** [comment]
> We can [...] release 2.4.0 (or 3.0.0 version - we have a lot of changes and new features, rewrite etc. what do you think?

3.0.0 seems possible... have you been using any sort of guiding principles until now in deciding when and how to update version numbers?

> Thank you for your contribution again!

Thank you for yours! I'm happy to contribute back freely seeing that I got free access to the plugin in the first place due to the contributions of you and the others.

> P.S. It would be much better to release a new version to public soon, more users = more testers = less bugs :)

Agreed. Now is a good time to release - we've reached all the goals we discussed privately for the next release.

**Comment by Eldenroot** [comment]
> 3.0.0 seems possible... have you been using any sort of guiding principles until now in deciding when and how to update version numbers?

No, I dont have any. However tag a new release as a version number 3.0.0 would be better in our case - new start for this plugin with a lof of bug fixes, rewrites, code clean up etc.

**Comment by lairdshaw** [comment]
That's fine by me. :-)

**Pull request merged**
