### PR TITLE
Fixes #168 by adding support for automatic upgrade on activate.

### LINKED ISSUE #168: Upgrading the plugin when the new version has new settings loses old settings values
Currently, the only way to gain access to new settings in a new version of the plugin is to first uninstall the plugin before copying the new files and reinstalling it, however, uninstalling the plugin causes all of its settings (including their values) to be lost. This is not so user-friendly, and it would be better for us provide a way for admins to upgrade without having to re-enter their settings values afterwards.

### PR DESCRIPTION
**Pull request by lairdshaw**
* Documents this feature in README.md under the heading "Upgrading".
* Also adds to README.md instructions for installing.
* Bumps the version to 2.4.0.

See whether you guys are happy with this approach to upgrading without loss of data. The new basic procedure for upgrade-without-data-loss is:

Deactivate the plugin => copy new files => (re)activate plugin.

The automatic upgrade occurs on the last step.

### CODE REVIEW

**Comment by Eldenroot** [comment]
Good job

**Comment by lairdshaw** [comment]
> Maybe, is possible to display a notification bar about successful update in ACP after activation?

It looks like it might be possible by hooking in to the 'admin_config_plugins_activate_commit' hook and altering the global $message variable which is to be shown when the plugin page reloads.

> What if update fail, is there any way to run it manually?

No, there's no way to run it manually, and no detection of any failures either, but it should be pretty fail-proof seeing that a lot of it is conditional - along the lines of "If this doesn't exist, then create it" or "If this exists, then delete it and recreate it", much like the original (pretty fail-proof) installation procedure already was.

**Comment by lairdshaw** [comment]
If the upgrade fails, it should be possible to retry by deactivating then reactivating.

**Comment by Eldenroot** [comment]
OK, so this can be doable via displaying notification when the update progress run successfully, because how user will know if it updated (I mean new settings is added to ACP etc). without that? What do you think?

**Comment by lairdshaw** [comment]
This is a screenshot of what I've been able to get working (not yet committed). First time uploading+embedding an image in a GitHub comment so I hope this works.

What do you think? Is the addition to the success message too hard to see? Are the italics and/or CAPS too much?

screen shot 2018-07-16 at 23 56 18-fullpage

**Comment by Eldenroot** [comment]
Yes, I meant something like that, good job.

Just change the text - maybe something like this would be enough: 
Thank You/Like system has been activated successfully and updated to version X.X.X. 

Version number will be handled automatically and taken from version number or change the lang file for every update? We can make a changelog on GitHub and add a link to show release notes in that notification bar - something like "View the changelog"

**Comment by lairdshaw** [comment]
OK, text changed, and yes, the version number is handled automatically - no need to update language files.

A changelog is a good idea.

I'm thinking that we might want to include a "Successfully upgraded to version x.y.z" message within the plugin listing too along with the changelog link - maybe just above "Configure Settings". It would only appear immediately after activation+upgrade, like the message up the top, and after that only the changelog link would appear in its place.

Thoughts?

**Comment by lairdshaw** [comment]
Here's how it's currently looking (again, not yet committed). We can probably revert the top message to its default ("The selected plugin has been installed and activated successfully.") now that there's a success message within the plugin's info, but we can keep both if you want.

screen shot 2018-07-17 at 01 00 22-fullpage

**Comment by Eldenroot** [comment]
Keep them both, because if user has more plugins, it will be hard to see in the long list of plugins.

**Comment by lairdshaw** [comment]
Done. Changes committed and pushed.

**Comment by Eldenroot** [comment]
Great, I will test it ASAP, I will let you know during today/tomorrow. Is there anything else in your mind what to add? ;)

**Comment by lairdshaw** [comment]
At the moment, just some tidying up of the code: fixing some indentation, correcting a few function calls from $db->escape_string() to htmlspecialchars_uni() - that kind of thing. Not a priority and could be postponed until after the next release if you prefer.

**Comment by lairdshaw** [comment]
Oh, and the kitchen sink. ;-)

**Comment by SvePu** [comment]
Great work @lairdshaw ... Thank you very much!

**Comment by Eldenroot** [comment]
> from $db->escape_string() to htmlspecialchars_uni() - that kind of thing. Not a priority and could be postponed until after the next release if you prefer.

we can wait and release it together... as it seems that MyBB is not compatible with php 7.2 so we can wait with the fix you added to repo in one of your previous commits.

**Comment by SvePu** [comment]
@Eldenroot  If you've tested it and it works, please merge it. In the next few days I can't test anything because I'm not at home on my PC.

**Comment by Eldenroot** [comment]
OK, merged, thank you!

We can delay v2.4.0 release (as I wrote above), so feel free to open any other PR. if you are interested here is our Discord channel - https://discord.gg/S9NvDTk

**Pull request merged**
